Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,11 +29,12 @@ jobs:
         run: |
           declare -a dirs
           for d in scripts/*/ ; do
-            if [ ${d} = *"${{ steps.files.outputs.all }}"* ];
+            if [ ${d} == *"${{ steps.files.outputs.all }}"* ];
             then
                 dirs+=("$d")
             fi
           done
+          # if more than 1 folder has changed, fail the pipeline? ( || exit 1 )
           dirs_json=$(printf '%s\n' "${dirs[@]}" | jq -R . | jq -s . | tr -d '\r\n')
           echo "dirs_json: ${dirs_json}"
           echo "::set-output name=dirs::${dirs_json}"
@@ -54,4 +55,5 @@ jobs:
       - uses: actions/upload-artifact@v3
         if: ${{ contains(needs.setup.outputs.changes, matrix.dir) }}
         with:
+          name: ${{ matrix.dir }} 
           path: ${{ matrix.dir }} 
